#!/usr/bin/env python
import click
from operations import list_account_details

@click.group
def cli():
    pass

@cli.command
def version():
    click.echo("Warmind - 0.0.1 ")

@click.group
def account():
    pass

@account.command()
def list():
    list_account_details()

if __name__ == "__main__":
    cli.add_command(account)
    cli()